//mod comments;
//mod formatted;
//mod debug;
//mod display;
//mod display1;
//mod display2;
//mod testcase_list;
//mod testcase_list_activity;
//mod formatting;
//mod threads;
//mod primitives;
//mod literals_and_operators;
//mod tuples;
mod arrays_and_slices;
fn main() {
    //    comments::comments();
    //    formatted::formatted();
    //    debug::run();
    //    display::run();
    //    display1::run();
    //    display2::run();
    //    testcase_list::run();
    //    testcase_list_activity::run();
    //    formatting::run();
    //    threads::run();
    //    primitives::run();
    //    literals_and_operators::run();
    //    tuples::run();
    arrays_and_slices::run();
}
