[package]
name = "tokio"
version = "0.1.0"
authors = ["Luke Hamilton <luke@mettadata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["full"], path = "/Users/metta/Dropbox/Code/__oss__/tokio/tokio" }
tokio-util = { version = "0.3", features = ["codec"], path ="/Users/metta/Dropbox/Code/__oss__/tokio/tokio-util" }